# Generated by Django 4.2 on 2024-04-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
    ]
